Repository smithy-lang/smithy-kotlin, pull requests merged in 2024-09, with the labels that each got.

#1147 chore: Modified bug issue template to add checkbox to report potentia…
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/issue-regression-labeler.yml
Labels: no-changelog

#1150 feat: OkHttp4Engine
  .changes/7acc674e-0dfe-461a-a5c3-f946e14a3ec7.json
  gradle/libs.versions.toml
  runtime/protocol/http-client-engines/http-client-engine-okhttp/api/http-client-engine-okhttp.api
  runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/HttpEngineEventListener.kt
  runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/MetricsInterceptor.kt
  runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngine.kt
  runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpHeadersAdapter.kt
  runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpUtils.kt
  runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/StreamingRequestBody.kt
  runtime/protocol/http-client-engines/http-client-engine-okhttp4/README.md
  runtime/protocol/http-client-engines/http-client-engine-okhttp4/api/http-client-engine-okhttp4.api
  runtime/protocol/http-client-engines/http-client-engine-okhttp4/build.gradle.kts
  runtime/protocol/http-client-engines/http-client-engine-okhttp4/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp4/OkHttp4Engine.kt
  runtime/protocol/http-client-engines/test-suite/build.gradle.kts
  runtime/protocol/http-client-engines/test-suite/jvm/src/aws/smithy/kotlin/runtime/http/test/util/AbstractEngineTestJVM.kt
  settings.gradle.kts
  tests/benchmarks/http-benchmarks/README.md
  tests/benchmarks/http-benchmarks/build.gradle.kts
  tests/benchmarks/http-benchmarks/jvm/src/aws/smithy/kotlin/benchmarks/http/HttpEngineBenchmarks.kt
Labels: acknowledge-artifact-size-increase

#1149 fix: stop including playground.js in Dokka pages and correctly filter for internal APIs
  dokka-smithy/src/main/kotlin/aws/smithy/kotlin/dokka/DisablePlaygroundIntegration.kt
  dokka-smithy/src/main/kotlin/aws/smithy/kotlin/dokka/FilterInternalApis.kt
  dokka-smithy/src/main/kotlin/aws/smithy/kotlin/dokka/SmithyDokkaPlugin.kt
Labels: no-changelog

#1151 fix: Add OkHttp 4.x to transformation configuration
  .brazil.json
Labels: no-changelog, acknowledge-artifact-size-increase

#1152 fix: add resolves-conflict-dependency for OkHttp 4.x
  .brazil.json
Labels: no-changelog

#1154 misc: add temporary resolves-conflict-dependencies to facilitate import
  .brazil.json
Labels: no-changelog
