Repository smithy-lang/smithy-kotlin, pull requests merged in 2025-02, with the labels that each got.

#1228 kn: gzip compression
  .changes/d3ce7511-6fb2-4435-8f46-db724551b384.json
  .github/workflows/continuous-integration.yml
  CHANGELOG.md
  codegen/protocol-tests/model/error-correction-tests.smithy
  codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/core/AwsHttpBindingProtocolGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpStringValuesMapSerializer.kt
  codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/SymbolProviderTest.kt
  codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGeneratorTest.kt
  codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpStringValuesMapSerializerTest.kt
  gradle.properties
  gradle/libs.versions.toml
  runtime/auth/aws-signing-default/api/aws-signing-default.api
  runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/Canonicalizer.kt
  runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/DefaultAwsSigner.kt
  runtime/auth/aws-signing-default/common/test/aws/smithy/kotlin/runtime/auth/awssigning/DefaultCanonicalizerTest.kt
  runtime/auth/http-auth-aws/common/test/aws/smithy/kotlin/runtime/http/auth/AwsHttpSignerTestBase.kt
  runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/MetricsInterceptor.kt
  runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngine.kt
  runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpUtils.kt
  runtime/protocol/http-client-engines/http-client-engine-okhttp4/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp4/OkHttp4Engine.kt
  runtime/protocol/http-client/build.gradle.kts
  runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/interceptors/HttpChecksumRequiredInterceptorTest.kt
  runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/interceptors/RequestCompressionInterceptorTest.kt
  runtime/protocol/http-client/jvm/test/aws/smithy/kotlin/runtime/http/interceptors/RequestCompressionInterceptorTestJvm.kt
  runtime/protocol/http-client/native/test/aws/smithy/kotlin/runtime/http/interceptors/RequestCompressionInterceptorTestNative.kt
  runtime/runtime-core/api/runtime-core.api
  runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/compression/GzipTestUtils.kt
  runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/content/ByteStream.kt
  runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/text/encoding/Base64.kt
  runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/util/JMESPath.kt
  runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/compression/GzipTest.kt
  runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/io/GzipByteReadChannelTest.kt
  runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/io/GzipSdkSourceTest.kt
  runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/text/encoding/Base64Test.kt
  runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/compression/GzipTestUtilsJvm.kt
  runtime/runtime-core/native/src/aws/smithy/kotlin/runtime/compression/GzipCompressor.kt
  runtime/runtime-core/native/src/aws/smithy/kotlin/runtime/compression/GzipNative.kt
  runtime/runtime-core/native/src/aws/smithy/kotlin/runtime/compression/GzipTestUtilsNative.kt
  runtime/runtime-core/native/src/aws/smithy/kotlin/runtime/io/GzipByteReadChannelNative.kt
  runtime/runtime-core/native/src/aws/smithy/kotlin/runtime/io/GzipSdkSourceNative.kt
  runtime/runtime-core/native/test/aws/smithy/kotlin/runtime/io/GzipTestUtilsNative.kt
Labels: no-changelog

#1210 feat: provide client config property for region provider
  codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/customization/RegionSupport.kt
  codegen/smithy-aws-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/aws/customization/RegionSupportTest.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
  runtime/smithy-client/api/smithy-client.api
  runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/region/RegionProvider.kt
  runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/region/RegionProviderChain.kt
  runtime/smithy-client/common/test/aws/smithy/kotlin/runtime/client/region/RegionProviderChainTest.kt
Labels: no-changelog, acknowledge-artifact-size-increase

#1229 kn: HostResolver
  .github/workflows/continuous-integration.yml
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  runtime/build.gradle.kts
  runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/net/HostResolverTest.kt
  runtime/runtime-core/native/src/aws/smithy/kotlin/runtime/net/HostResolverNative.kt
Labels: no-changelog

#1204 misc: gradle mirror
  .github/workflows/artifact-size-metrics.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/kat-transform.yml
  .github/workflows/lint.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: no-changelog

#1231 kn: implement `SystemDefaultProvider` for Native
  gradle.properties
  runtime/runtime-core/api/runtime-core.api
  runtime/runtime-core/build.gradle.kts
  runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/util/Platform.kt
  runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/util/SystemPlatformProviderTest.kt
  runtime/runtime-core/linuxX64/test/aws/smithy/kotlin/runtime/util/SystemPlatformProviderLinuxX64Test.kt
  runtime/runtime-core/native/src/aws/smithy/kotlin/runtime/util/PlatformNative.kt
  runtime/runtime-core/native/src/nativeInterop/cinterop/environ.h
Labels: no-changelog

#1236 misc: gradle version bump
  gradle/wrapper/gradle-wrapper.properties
Labels: no-changelog

#1239 misc: bump build plugin version
  gradle/libs.versions.toml
Labels: no-changelog

#1241 misc: test union member name same as union
  tests/compile/src/test/kotlin/software/amazon/smithy/kotlin/codegen/SmithySdkTest.kt
Labels: no-changelog

#1242 fix: unions with member names matching auto-imported Kotlin symbols
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
  codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/SymbolProviderTest.kt
  tests/compile/src/test/kotlin/software/amazon/smithy/kotlin/codegen/SmithySdkTest.kt
Labels: no-changelog

#1247 misc: Remove Elastic Inference SDK ID test
  codegen/smithy-kotlin-codegen/src/test/resources/sdk-ids-test-output.csv
  codegen/smithy-kotlin-codegen/src/test/resources/sdk-ids.csv
Labels: no-changelog

#1246 feat: Kotlin implementation of SigV4a signing
  .changes/4b6debe1-7706-484a-8599-ef8c14cecde2.json
  runtime/auth/aws-signing-common/api/aws-signing-common.api
  runtime/auth/aws-signing-common/common/src/aws/smithy/kotlin/runtime/auth/awssigning/AwsSigningConfig.kt
  runtime/auth/aws-signing-common/common/src/aws/smithy/kotlin/runtime/auth/awssigning/AwsSigningExceptions.kt
  runtime/auth/aws-signing-default/build.gradle.kts
  runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/BaseSigV4SignatureCalculator.kt
  runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/Canonicalizer.kt
  runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/DefaultAwsSigner.kt
  runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/RequestMutator.kt
  runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/SigV4SignatureCalculator.kt
  runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/SigV4aSignatureCalculator.kt
  runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/SignatureCalculator.kt
  runtime/auth/aws-signing-default/common/test/aws/smithy/kotlin/runtime/auth/awssigning/DefaultBasicSigningTest.kt
  runtime/auth/aws-signing-default/common/test/aws/smithy/kotlin/runtime/auth/awssigning/DefaultRequestMutatorTest.kt
  runtime/auth/aws-signing-default/common/test/aws/smithy/kotlin/runtime/auth/awssigning/SigV4SignatureCalculatorTest.kt
  runtime/auth/aws-signing-default/common/test/aws/smithy/kotlin/runtime/auth/awssigning/SigV4aSignatureCalculatorTest.kt
  runtime/auth/aws-signing-default/jvm/test/aws/smithy/kotlin/runtime/auth/awssigning/DefaultSigningSuiteTest.kt
  runtime/runtime-core/api/runtime-core.api
  runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/hashing/Ecdsa.kt
  runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/hashing/EcdsaJVM.kt
  runtime/runtime-core/jvm/test/aws/smithy/kotlin/runtime/hashing/EcdsaJVMTest.kt
  runtime/runtime-core/native/src/aws/smithy/kotlin/runtime/hashing/EcdsaNative.kt
Labels: acknowledge-artifact-size-increase

#1245 fix: account ID based endpoints
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitor.kt
  codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/OperationContextParamsTest.kt
  tests/codegen/waiter-tests/model/function-keys.smithy
  tests/codegen/waiter-tests/src/test/kotlin/com/test/FunctionKeysTest.kt
Labels: no-changelog
