Repository smithy-lang/smithy-kotlin, pull requests merged in 2025-04, with the labels that each got.

#1261 misc: run merge main on push to main
  .github/workflows/merge-main.yml
Labels: no-changelog

#1260 feat: sync mirror
  .github/workflows/sync-mirror.yml
Labels: no-changelog

#1262 chore: reintegrate E2E smoke tests into the top-level Gradle build; modularize smoke test runners to improve testability
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/lang/KotlinTypes.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/smoketests/SmokeTestsRunnerGenerator.kt
  codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/smoketests/SmokeTestsRunnerGeneratorTest.kt
  runtime/runtime-core/api/runtime-core.api
  runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/smoketests/SmokeTestsFunctions.kt
Labels: no-changelog

#1263 misc: include `aws-crt-kotlin` as a composite build
  settings.gradle.kts
Labels: no-changelog

#1266 misc: prepare codegen packages for internal import
  .brazil.json
  codegen/smithy-aws-kotlin-codegen/build.gradle.kts
  gradle/libs.versions.toml
Labels: no-changelog

#1268 misc: use aws-kotlin-repo-tools show-results action
  .github/workflows/artifact-size-metrics.yml
Labels: no-changelog, acknowledge-artifact-size-increase

#1270 chore: upgrade aws-kotlin-repo-tools
  gradle/libs.versions.toml
Labels: no-changelog

#1267 misc: add lineSeparator to Filesystem
  runtime/runtime-core/api/runtime-core.api
  runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/util/Platform.kt
Labels: no-changelog

#1273 kn: merge from main
  .brazil.json
  .github/workflows/artifact-size-metrics.yml
  .github/workflows/merge-main.yml
  .github/workflows/sync-mirror.yml
  CHANGELOG.md
  codegen/smithy-aws-kotlin-codegen/build.gradle.kts
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/lang/KotlinTypes.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/smoketests/SmokeTestsRunnerGenerator.kt
  codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/smoketests/SmokeTestsRunnerGeneratorTest.kt
  gradle.properties
  gradle/libs.versions.toml
  runtime/runtime-core/api/runtime-core.api
  runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/smoketests/SmokeTestsFunctions.kt
  settings.gradle.kts
Labels: no-changelog

#1274 fix: merge main workflow credentials
  .github/workflows/merge-main.yml
Labels: no-changelog

#1271 feat: add service protocol benchmarks
  runtime/observability/telemetry-api/api/telemetry-api.api
  runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/metrics/Histogram.kt
  runtime/protocol/http-client/api/http-client.api
  runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/interceptors/OperationTelemetryInterceptor.kt
  runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/operation/OperationMetrics.kt
Labels: no-changelog

#1277 feat: Add `authSchemePreference` configuration
  .changes/d40dc5d3-4c91-4e98-8420-ee465714c9bc.json
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientConfigGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/auth/AuthSchemeProviderConfigIntegration.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/auth/AuthSchemeProviderGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/util/RuntimeConfigProperty.kt
  codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientConfigGeneratorTest.kt
  gradle/libs.versions.toml
  runtime/auth/http-auth-api/api/http-auth-api.api
  runtime/auth/http-auth-api/common/src/aws/smithy/kotlin/runtime/http/auth/HttpAuthConfig.kt
  runtime/auth/http-auth/api/http-auth.api
  runtime/auth/http-auth/common/src/aws/smithy/kotlin/runtime/http/auth/ReprioritizeAuthOptions.kt
  runtime/auth/http-auth/common/test/aws/smithy/kotlin/runtime/http/auth/ReprioritizeAuthOptionsTest.kt
Labels: acknowledge-artifact-size-increase
