Repository smithy-lang/smithy-kotlin, pull requests merged in 2025-07, with the labels that each got.

#1309 chore: bump aws-kotlin-repo-tools version
  gradle/libs.versions.toml
Labels: no-changelog

#1310 chore: remove `@deprecated` APIs in preparation for v1.5
  codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/AwsQuery.kt
  codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/Ec2Query.kt
  codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/RestXml.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
  runtime/auth/aws-signing-common/api/aws-signing-common.api
  runtime/auth/aws-signing-common/common/src/aws/smithy/kotlin/runtime/auth/awssigning/AwsSigningExceptions.kt
  runtime/auth/aws-signing-tests/jvm/src/aws/smithy/kotlin/runtime/auth/awssigning/tests/SigningSuiteTestBaseJVM.kt
  runtime/auth/http-auth-aws/common/test/aws/smithy/kotlin/runtime/http/auth/AwsHttpSignerTestBase.kt
  runtime/protocol/aws-json-protocols/common/test/aws/smithy/kotlin/runtime/awsprotocol/json/AwsJsonProtocolTest.kt
  runtime/protocol/aws-xml-protocols/api/aws-xml-protocols.api
  runtime/protocol/aws-xml-protocols/common/src/aws/smithy/kotlin/runtime/awsprotocol/xml/Ec2QueryErrorDeserializer.kt
  runtime/protocol/aws-xml-protocols/common/src/aws/smithy/kotlin/runtime/awsprotocol/xml/RestXmlErrorDeserializer.kt
  runtime/protocol/aws-xml-protocols/common/test/aws/smithy/kotlin/runtime/awsprotocol/xml/Ec2QueryErrorDeserializerTest.kt
  runtime/protocol/aws-xml-protocols/common/test/aws/smithy/kotlin/runtime/awsprotocol/xml/RestXmlErrorDeserializerTest.kt
  runtime/protocol/http-client/api/http-client.api
  runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/operation/HttpSerde.kt
  runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/operation/SdkHttpOperation.kt
  runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/operation/SdkHttpOperationTest.kt
  runtime/runtime-core/api/runtime-core.api
  runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/smoketests/SmokeTestsFunctions.kt
  runtime/serde/serde-xml/api/serde-xml.api
  runtime/serde/serde-xml/common/src/aws/smithy/kotlin/runtime/serde/xml/XmlDeserializer.kt
  runtime/serde/serde-xml/common/src/aws/smithy/kotlin/runtime/serde/xml/XmlStreamReader.kt
Labels: no-changelog, acknowledge-api-break, acknowledge-artifact-size-increase

#1313 feat: upgrade to Kotlin 2.2.0
  .changes/2ec4ad9a-f964-4cf1-be58-d0229493bb81.json
  bom/build.gradle.kts
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinDependency.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/GradleGenerator.kt
  codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/KotlinSettingsTest.kt
  gradle/libs.versions.toml
  runtime/auth/aws-credentials/api/aws-credentials.api
  runtime/auth/aws-signing-tests/build.gradle.kts
  runtime/auth/http-auth-api/api/http-auth-api.api
  runtime/auth/http-auth-aws/api/http-auth-aws.api
  runtime/auth/http-auth/api/http-auth.api
  runtime/auth/identity-api/api/identity-api.api
  runtime/build.gradle.kts
  runtime/observability/telemetry-api/api/telemetry-api.api
  runtime/protocol/aws-json-protocols/api/aws-json-protocols.api
  runtime/protocol/aws-protocol-core/api/aws-protocol-core.api
  runtime/protocol/http-client-engines/http-client-engine-okhttp/api/http-client-engine-okhttp.api
  runtime/protocol/http-client/api/http-client.api
  runtime/protocol/http/api/http.api
  runtime/protocol/smithy-rpcv2-protocols/api/smithy-rpcv2-protocols.api
  runtime/runtime-core/api/runtime-core.api
  runtime/serde/serde-xml/api/serde-xml.api
  runtime/smithy-client/api/smithy-client.api
  tests/codegen/waiter-tests/build.gradle.kts
Labels: acknowledge-api-break, acknowledge-artifact-size-increase

#1315 fix: always serialize defaults
  .changes/d4f09e32-8bcc-406e-96e0-2743280c13d9.json
  codegen/smithy-kotlin-codegen-testutils/src/main/kotlin/software/amazon/smithy/kotlin/codegen/test/ModelTestUtils.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/KotlinSettings.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinDependency.kt
  codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpStringValuesMapSerializerTest.kt
  codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerializeStructGeneratorTest.kt
Labels: acknowledge-artifact-size-increase

#1314 Service sdk cbor serde
  codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/RpcV2Cbor.kt
  codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/core/StaticHttpBindingResolver.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/CodegenVisitor.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/KotlinSettings.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinDependency.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingResolver.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/CborParserGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/CborSerializerGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/ServiceStubGenerator.kt
Labels: no-changelog

#1319 Service sdk error
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/CodegenVisitor.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinDependency.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/GradleGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/KtorStubGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/ServiceStubConfigurations.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/ServiceStubGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/ServiceTypes.kt
Labels: no-changelog

#1317 feat: add support for bedrock api key auth
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
  runtime/auth/http-auth/api/http-auth.api
  runtime/auth/http-auth/common/src/aws/smithy/kotlin/runtime/http/auth/EnvironmentBearerTokenProvider.kt
  runtime/auth/http-auth/common/test/aws/smithy/kotlin/runtime/http/auth/EnvironmentBearerTokenProviderTest.kt
Labels: no-changelog, acknowledge-artifact-size-increase

#1321 Service sdk authentication
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinDependency.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/KtorStubGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/ServiceTypes.kt
Labels: no-changelog

#1327 kn: upgrade to latest version of aws-kotlin-repo-tools
  .github/workflows/continuous-integration.yml
  gradle/libs.versions.toml
  runtime/build.gradle.kts
Labels: no-changelog

#1331 chore: v1.5-main merge
  runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngine.kt
Labels: no-changelog, acknowledge-api-break, acknowledge-artifact-size-increase

#1333 kn: depend on SNAPSHOT version of aws-crt-kotlin
  gradle/libs.versions.toml
Labels: no-changelog

#1330 Service sdk testing
  build.gradle.kts
  codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/RpcV2Cbor.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinDependency.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/lang/KotlinTypes.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/CborSerializerGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/KtorStubGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/ServiceStubGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/ServiceTypes.kt
  gradle/libs.versions.toml
  settings.gradle.kts
  tests/codegen/service-codegen-tests/build.gradle.kts
  tests/codegen/service-codegen-tests/model/service-generator-test.smithy
  tests/codegen/service-codegen-tests/src/main/kotlin/com/test/DefaultServiceGeneratorTest.kt
  tests/codegen/service-codegen-tests/src/test/kotlin/com/test/ServiceFileTest.kt
  tests/codegen/service-codegen-tests/src/test/kotlin/com/test/ServiceGeneratorTest.kt
Labels: no-changelog, acknowledge-artifact-size-increase

#1341 fix typo: OkHttpEngine4 -> OkHttp4Engine
  runtime/protocol/http-client-engines/http-client-engine-okhttp4/README.md
Labels: no-changelog

#1338 Service sdk constraints
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/KtorStubGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/ServiceTypes.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/contraints/AbstractConstraintTraitGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/contraints/ConstraintGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/contraints/ConstraintUtilsGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/contraints/LengthConstraintGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/contraints/PatternConstraintGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/contraints/RangeConstraintGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/contraints/RequiredConstraintGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/contraints/UniqueItemsConstraintGenerator.kt
  codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/service/contraints/utils.kt
  tests/codegen/service-codegen-tests/model/service-constraints-test.smithy
  tests/codegen/service-codegen-tests/model/service-generator-test.smithy
  tests/codegen/service-codegen-tests/src/main/kotlin/com/test/DefaultServiceGeneratorTest.kt
  tests/codegen/service-codegen-tests/src/test/kotlin/com/test/ServiceConstraintsTest.kt
  tests/codegen/service-codegen-tests/src/test/kotlin/com/test/ServiceDataClasses.kt
  tests/codegen/service-codegen-tests/src/test/kotlin/com/test/ServiceEngineFactoryTest.kt
  tests/codegen/service-codegen-tests/src/test/kotlin/com/test/ServiceFileTest.kt
  tests/codegen/service-codegen-tests/src/test/kotlin/com/test/ServiceGeneratorTest.kt
  tests/codegen/service-codegen-tests/src/test/kotlin/com/test/utils.kt
Labels: no-changelog
